### ISSUE TITLE
Is this padding wrong?

### ISSUE THREAD

**Issue by wlnirvana** [HE7086/pdf-md5-hashquine#1]
https://github.com/HE7086/pdf-md5-hashquine/blob/b2b16f99a1deba31c3f4a3c3aa26a2c6c8137b3c/project/gen.py#L108-L114

In the last line, padding is appended as `data += b'\x00' * (64 - l - 4)`. But shouldn't it be `64+l-4` to align with 64-byte block boundary?

**Comment by HE7086** [comment]
You are right, this might be an edge case that didn't happen at all in my test runs.
I thought of this case but didn't actually run into it.

**Comment by wlnirvana** [comment]
Closed by 82ba3fc
