### ISSUE TITLE
Image padding calculation confusion

### ISSUE THREAD

**Issue by wlnirvana** [HE7086/pdf-md5-hashquine#2]
Shouldn't this condition be `image_data_size % 64 > 60`?

https://github.com/HE7086/pdf-md5-hashquine/blob/82ba3fcf52dfbc518efac7a98af10e4c127d1e76/project/gen.py#L23

**Comment by HE7086** [comment]
Seems true, this is the exact same problem that happened in #1 , which didn't happen in my test runs.

There's a lot of hard-coded values and untested code paths in this project, let me know if you find any problem :)
